// <auto-generated />
using System;
using EnrollmentSystem.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EnrollmentSystem.Api.Migrations
{
    [DbContext(typeof(EnrollmentDbContext))]
    [Migration("20260704120027_UpdateModelsAndSeedData")]
    partial class UpdateModelsAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EnrollmentSystem.Api.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bachelor of Science in Information Technology"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bachelor of Science in Criminology"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bachelor of Science in Psychology"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bachelor of Science in Computer Science"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bachelor of Science in Accountancy"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Bachelor in Secondary Education"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Bachelor in Elementary Education"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Bachelor of Science in Civil Engineering"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Bachelor of Science in Computer Engineering"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Bachelor of Science in Tourism Management"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Bachelor of Science in Hospitality Management"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Bachelor of Science in Nursing"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Bachelor of Science in Business Administration"
                        });
                });

            modelBuilder.Entity("EnrollmentSystem.Api.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("EnrollmentSystem.Api.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GuardianName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("YearLevelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("YearLevelId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("EnrollmentSystem.Api.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Credits")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("EnrollmentSystem.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "registrar@mapplewood.edu",
                            PasswordHash = "$2a$11$16uHNH4dKW/v1z4Wrb/exujzPpsdGNo4g23aud/bC4olXKOTl8veu",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "john@mapplewood.edu",
                            PasswordHash = "$2a$11$16uHNH4dKW/v1z4Wrb/exujzPpsdGNo4g23aud/bC4olXKOTl8veu",
                            Role = "Student"
                        });
                });

            modelBuilder.Entity("EnrollmentSystem.Api.Models.YearLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("YearLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "1st Year"
                        },
                        new
                        {
                            Id = 2,
                            Name = "2nd Year"
                        },
                        new
                        {
                            Id = 3,
                            Name = "3rd Year"
                        },
                        new
                        {
                            Id = 4,
                            Name = "4th Year"
                        },
                        new
                        {
                            Id = 5,
                            Name = "5th Year"
                        });
                });

            modelBuilder.Entity("EnrollmentSystem.Api.Models.Enrollment", b =>
                {
                    b.HasOne("EnrollmentSystem.Api.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnrollmentSystem.Api.Models.Subject", "Subject")
                        .WithMany("Enrollments")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("EnrollmentSystem.Api.Models.Student", b =>
                {
                    b.HasOne("EnrollmentSystem.Api.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId");

                    b.HasOne("EnrollmentSystem.Api.Models.YearLevel", "YearLevel")
                        .WithMany()
                        .HasForeignKey("YearLevelId");

                    b.Navigation("Course");

                    b.Navigation("YearLevel");
                });

            modelBuilder.Entity("EnrollmentSystem.Api.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("EnrollmentSystem.Api.Models.Subject", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
