// <auto-generated />
using System;
using EnrollmentSystem.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EnrollmentSystem.Api.Migrations
{
    [DbContext(typeof(EnrollmentDbContext))]
    [Migration("20260704163257_UpdateApplicationStatus")]
    partial class UpdateApplicationStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EnrollmentSystem.Api.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bachelor of Science in Information Technology"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bachelor of Science in Criminology"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bachelor of Science in Psychology"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bachelor of Science in Computer Science"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bachelor of Science in Accountancy"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Bachelor in Secondary Education"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Bachelor in Elementary Education"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Bachelor of Science in Civil Engineering"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Bachelor of Science in Computer Engineering"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Bachelor of Science in Tourism Management"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Bachelor of Science in Hospitality Management"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Bachelor of Science in Nursing"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Bachelor of Science in Business Administration"
                        });
                });

            modelBuilder.Entity("EnrollmentSystem.Api.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("EnrollmentSystem.Api.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Form137Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoodMoralPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GuardianName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdPhotoPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProofOfPaymentPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("YearLevelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("YearLevelId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("EnrollmentSystem.Api.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<string>("Days")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EdpCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubjectTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Units")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Days = "M/W",
                            EdpCode = "2001",
                            EndTime = "09:30 AM",
                            Room = "Rm 200",
                            Section = "A1",
                            StartTime = "08:00 AM",
                            SubjectCode = "IT101",
                            SubjectTitle = "Intro to Computing",
                            Units = 3
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            Days = "T/Th",
                            EdpCode = "2002",
                            EndTime = "11:30 AM",
                            Room = "Rm 201",
                            Section = "A1",
                            StartTime = "10:00 AM",
                            SubjectCode = "IT102",
                            SubjectTitle = "Programming Fundamentals",
                            Units = 3
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 1,
                            Days = "M/W",
                            EdpCode = "2003",
                            EndTime = "02:30 PM",
                            Room = "Rm 202",
                            Section = "A1",
                            StartTime = "01:00 PM",
                            SubjectCode = "IT103",
                            SubjectTitle = "Data Structures",
                            Units = 3
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 1,
                            Days = "T/Th",
                            EdpCode = "2004",
                            EndTime = "04:00 PM",
                            Room = "Rm 203",
                            Section = "A1",
                            StartTime = "02:30 PM",
                            SubjectCode = "IT104",
                            SubjectTitle = "Database Systems",
                            Units = 3
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 1,
                            Days = "F",
                            EdpCode = "2005",
                            EndTime = "10:30 AM",
                            Room = "Rm 204",
                            Section = "A1",
                            StartTime = "09:00 AM",
                            SubjectCode = "IT105",
                            SubjectTitle = "Networking Basics",
                            Units = 2
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 1,
                            Days = "M/W",
                            EdpCode = "2006",
                            EndTime = "04:30 PM",
                            Room = "Rm 205",
                            Section = "A1",
                            StartTime = "03:00 PM",
                            SubjectCode = "IT106",
                            SubjectTitle = "Web Development",
                            Units = 3
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 2,
                            Days = "M/W",
                            EdpCode = "2101",
                            EndTime = "09:30 AM",
                            Room = "Rm 200",
                            Section = "B1",
                            StartTime = "08:00 AM",
                            SubjectCode = "CRIM101",
                            SubjectTitle = "Intro to Criminology",
                            Units = 3
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 2,
                            Days = "T/Th",
                            EdpCode = "2102",
                            EndTime = "11:30 AM",
                            Room = "Rm 201",
                            Section = "B1",
                            StartTime = "10:00 AM",
                            SubjectCode = "CRIM102",
                            SubjectTitle = "Criminal Law I",
                            Units = 3
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 2,
                            Days = "M/W",
                            EdpCode = "2103",
                            EndTime = "02:30 PM",
                            Room = "Rm 202",
                            Section = "B1",
                            StartTime = "01:00 PM",
                            SubjectCode = "CRIM103",
                            SubjectTitle = "Police Organization",
                            Units = 3
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 2,
                            Days = "T/Th",
                            EdpCode = "2104",
                            EndTime = "04:00 PM",
                            Room = "Rm 203",
                            Section = "B1",
                            StartTime = "02:30 PM",
                            SubjectCode = "CRIM104",
                            SubjectTitle = "Ethics in Law Enforcement",
                            Units = 3
                        },
                        new
                        {
                            Id = 11,
                            CourseId = 2,
                            Days = "F",
                            EdpCode = "2105",
                            EndTime = "10:30 AM",
                            Room = "Rm 204",
                            Section = "B1",
                            StartTime = "09:00 AM",
                            SubjectCode = "CRIM105",
                            SubjectTitle = "Forensic Science",
                            Units = 2
                        },
                        new
                        {
                            Id = 12,
                            CourseId = 2,
                            Days = "M/W",
                            EdpCode = "2106",
                            EndTime = "04:30 PM",
                            Room = "Rm 205",
                            Section = "B1",
                            StartTime = "03:00 PM",
                            SubjectCode = "CRIM106",
                            SubjectTitle = "Criminal Investigation",
                            Units = 3
                        },
                        new
                        {
                            Id = 13,
                            CourseId = 3,
                            Days = "M/W",
                            EdpCode = "2201",
                            EndTime = "09:30 AM",
                            Room = "Rm 200",
                            Section = "C1",
                            StartTime = "08:00 AM",
                            SubjectCode = "PSY101",
                            SubjectTitle = "General Psychology",
                            Units = 3
                        },
                        new
                        {
                            Id = 14,
                            CourseId = 3,
                            Days = "T/Th",
                            EdpCode = "2202",
                            EndTime = "11:30 AM",
                            Room = "Rm 201",
                            Section = "C1",
                            StartTime = "10:00 AM",
                            SubjectCode = "PSY102",
                            SubjectTitle = "Developmental Psychology",
                            Units = 3
                        },
                        new
                        {
                            Id = 15,
                            CourseId = 3,
                            Days = "M/W",
                            EdpCode = "2203",
                            EndTime = "02:30 PM",
                            Room = "Rm 202",
                            Section = "C1",
                            StartTime = "01:00 PM",
                            SubjectCode = "PSY103",
                            SubjectTitle = "Psychological Statistics",
                            Units = 3
                        },
                        new
                        {
                            Id = 16,
                            CourseId = 3,
                            Days = "T/Th",
                            EdpCode = "2204",
                            EndTime = "04:00 PM",
                            Room = "Rm 203",
                            Section = "C1",
                            StartTime = "02:30 PM",
                            SubjectCode = "PSY104",
                            SubjectTitle = "Abnormal Psychology",
                            Units = 3
                        },
                        new
                        {
                            Id = 17,
                            CourseId = 3,
                            Days = "F",
                            EdpCode = "2205",
                            EndTime = "10:30 AM",
                            Room = "Rm 204",
                            Section = "C1",
                            StartTime = "09:00 AM",
                            SubjectCode = "PSY105",
                            SubjectTitle = "Cognitive Psychology",
                            Units = 2
                        },
                        new
                        {
                            Id = 18,
                            CourseId = 3,
                            Days = "M/W",
                            EdpCode = "2206",
                            EndTime = "04:30 PM",
                            Room = "Rm 205",
                            Section = "C1",
                            StartTime = "03:00 PM",
                            SubjectCode = "PSY106",
                            SubjectTitle = "Experimental Psychology",
                            Units = 3
                        },
                        new
                        {
                            Id = 19,
                            CourseId = 4,
                            Days = "M/W",
                            EdpCode = "2301",
                            EndTime = "09:30 AM",
                            Room = "Rm 200",
                            Section = "D1",
                            StartTime = "08:00 AM",
                            SubjectCode = "CS101",
                            SubjectTitle = "Introduction to Computer Science",
                            Units = 3
                        },
                        new
                        {
                            Id = 20,
                            CourseId = 4,
                            Days = "T/Th",
                            EdpCode = "2302",
                            EndTime = "11:30 AM",
                            Room = "Rm 201",
                            Section = "D1",
                            StartTime = "10:00 AM",
                            SubjectCode = "CS102",
                            SubjectTitle = "Advanced Computer Science",
                            Units = 3
                        },
                        new
                        {
                            Id = 21,
                            CourseId = 4,
                            Days = "M/W",
                            EdpCode = "2303",
                            EndTime = "02:30 PM",
                            Room = "Rm 202",
                            Section = "D1",
                            StartTime = "01:00 PM",
                            SubjectCode = "CS103",
                            SubjectTitle = "Computer Science Principles",
                            Units = 3
                        },
                        new
                        {
                            Id = 22,
                            CourseId = 4,
                            Days = "T/Th",
                            EdpCode = "2304",
                            EndTime = "04:00 PM",
                            Room = "Rm 203",
                            Section = "D1",
                            StartTime = "02:30 PM",
                            SubjectCode = "CS104",
                            SubjectTitle = "Applied Computer Science",
                            Units = 3
                        },
                        new
                        {
                            Id = 23,
                            CourseId = 4,
                            Days = "F",
                            EdpCode = "2305",
                            EndTime = "10:30 AM",
                            Room = "Rm 204",
                            Section = "D1",
                            StartTime = "09:00 AM",
                            SubjectCode = "CS105",
                            SubjectTitle = "Computer Science Lab",
                            Units = 2
                        },
                        new
                        {
                            Id = 24,
                            CourseId = 4,
                            Days = "M/W",
                            EdpCode = "2306",
                            EndTime = "04:30 PM",
                            Room = "Rm 205",
                            Section = "D1",
                            StartTime = "03:00 PM",
                            SubjectCode = "CS106",
                            SubjectTitle = "Seminar in Computer Science",
                            Units = 3
                        },
                        new
                        {
                            Id = 25,
                            CourseId = 5,
                            Days = "M/W",
                            EdpCode = "2401",
                            EndTime = "09:30 AM",
                            Room = "Rm 200",
                            Section = "E1",
                            StartTime = "08:00 AM",
                            SubjectCode = "ACC101",
                            SubjectTitle = "Introduction to Accounting",
                            Units = 3
                        },
                        new
                        {
                            Id = 26,
                            CourseId = 5,
                            Days = "T/Th",
                            EdpCode = "2402",
                            EndTime = "11:30 AM",
                            Room = "Rm 201",
                            Section = "E1",
                            StartTime = "10:00 AM",
                            SubjectCode = "ACC102",
                            SubjectTitle = "Advanced Accounting",
                            Units = 3
                        },
                        new
                        {
                            Id = 27,
                            CourseId = 5,
                            Days = "M/W",
                            EdpCode = "2403",
                            EndTime = "02:30 PM",
                            Room = "Rm 202",
                            Section = "E1",
                            StartTime = "01:00 PM",
                            SubjectCode = "ACC103",
                            SubjectTitle = "Accounting Principles",
                            Units = 3
                        },
                        new
                        {
                            Id = 28,
                            CourseId = 5,
                            Days = "T/Th",
                            EdpCode = "2404",
                            EndTime = "04:00 PM",
                            Room = "Rm 203",
                            Section = "E1",
                            StartTime = "02:30 PM",
                            SubjectCode = "ACC104",
                            SubjectTitle = "Applied Accounting",
                            Units = 3
                        },
                        new
                        {
                            Id = 29,
                            CourseId = 5,
                            Days = "F",
                            EdpCode = "2405",
                            EndTime = "10:30 AM",
                            Room = "Rm 204",
                            Section = "E1",
                            StartTime = "09:00 AM",
                            SubjectCode = "ACC105",
                            SubjectTitle = "Accounting Lab",
                            Units = 2
                        },
                        new
                        {
                            Id = 30,
                            CourseId = 5,
                            Days = "M/W",
                            EdpCode = "2406",
                            EndTime = "04:30 PM",
                            Room = "Rm 205",
                            Section = "E1",
                            StartTime = "03:00 PM",
                            SubjectCode = "ACC106",
                            SubjectTitle = "Seminar in Accounting",
                            Units = 3
                        },
                        new
                        {
                            Id = 31,
                            CourseId = 6,
                            Days = "M/W",
                            EdpCode = "2501",
                            EndTime = "09:30 AM",
                            Room = "Rm 200",
                            Section = "F1",
                            StartTime = "08:00 AM",
                            SubjectCode = "SED101",
                            SubjectTitle = "Introduction to Secondary Education",
                            Units = 3
                        },
                        new
                        {
                            Id = 32,
                            CourseId = 6,
                            Days = "T/Th",
                            EdpCode = "2502",
                            EndTime = "11:30 AM",
                            Room = "Rm 201",
                            Section = "F1",
                            StartTime = "10:00 AM",
                            SubjectCode = "SED102",
                            SubjectTitle = "Advanced Secondary Education",
                            Units = 3
                        },
                        new
                        {
                            Id = 33,
                            CourseId = 6,
                            Days = "M/W",
                            EdpCode = "2503",
                            EndTime = "02:30 PM",
                            Room = "Rm 202",
                            Section = "F1",
                            StartTime = "01:00 PM",
                            SubjectCode = "SED103",
                            SubjectTitle = "Secondary Education Principles",
                            Units = 3
                        },
                        new
                        {
                            Id = 34,
                            CourseId = 6,
                            Days = "T/Th",
                            EdpCode = "2504",
                            EndTime = "04:00 PM",
                            Room = "Rm 203",
                            Section = "F1",
                            StartTime = "02:30 PM",
                            SubjectCode = "SED104",
                            SubjectTitle = "Applied Secondary Education",
                            Units = 3
                        },
                        new
                        {
                            Id = 35,
                            CourseId = 6,
                            Days = "F",
                            EdpCode = "2505",
                            EndTime = "10:30 AM",
                            Room = "Rm 204",
                            Section = "F1",
                            StartTime = "09:00 AM",
                            SubjectCode = "SED105",
                            SubjectTitle = "Secondary Education Lab",
                            Units = 2
                        },
                        new
                        {
                            Id = 36,
                            CourseId = 6,
                            Days = "M/W",
                            EdpCode = "2506",
                            EndTime = "04:30 PM",
                            Room = "Rm 205",
                            Section = "F1",
                            StartTime = "03:00 PM",
                            SubjectCode = "SED106",
                            SubjectTitle = "Seminar in Secondary Education",
                            Units = 3
                        },
                        new
                        {
                            Id = 37,
                            CourseId = 7,
                            Days = "M/W",
                            EdpCode = "2601",
                            EndTime = "09:30 AM",
                            Room = "Rm 200",
                            Section = "G1",
                            StartTime = "08:00 AM",
                            SubjectCode = "EED101",
                            SubjectTitle = "Introduction to Elementary Education",
                            Units = 3
                        },
                        new
                        {
                            Id = 38,
                            CourseId = 7,
                            Days = "T/Th",
                            EdpCode = "2602",
                            EndTime = "11:30 AM",
                            Room = "Rm 201",
                            Section = "G1",
                            StartTime = "10:00 AM",
                            SubjectCode = "EED102",
                            SubjectTitle = "Advanced Elementary Education",
                            Units = 3
                        },
                        new
                        {
                            Id = 39,
                            CourseId = 7,
                            Days = "M/W",
                            EdpCode = "2603",
                            EndTime = "02:30 PM",
                            Room = "Rm 202",
                            Section = "G1",
                            StartTime = "01:00 PM",
                            SubjectCode = "EED103",
                            SubjectTitle = "Elementary Education Principles",
                            Units = 3
                        },
                        new
                        {
                            Id = 40,
                            CourseId = 7,
                            Days = "T/Th",
                            EdpCode = "2604",
                            EndTime = "04:00 PM",
                            Room = "Rm 203",
                            Section = "G1",
                            StartTime = "02:30 PM",
                            SubjectCode = "EED104",
                            SubjectTitle = "Applied Elementary Education",
                            Units = 3
                        },
                        new
                        {
                            Id = 41,
                            CourseId = 7,
                            Days = "F",
                            EdpCode = "2605",
                            EndTime = "10:30 AM",
                            Room = "Rm 204",
                            Section = "G1",
                            StartTime = "09:00 AM",
                            SubjectCode = "EED105",
                            SubjectTitle = "Elementary Education Lab",
                            Units = 2
                        },
                        new
                        {
                            Id = 42,
                            CourseId = 7,
                            Days = "M/W",
                            EdpCode = "2606",
                            EndTime = "04:30 PM",
                            Room = "Rm 205",
                            Section = "G1",
                            StartTime = "03:00 PM",
                            SubjectCode = "EED106",
                            SubjectTitle = "Seminar in Elementary Education",
                            Units = 3
                        },
                        new
                        {
                            Id = 43,
                            CourseId = 8,
                            Days = "M/W",
                            EdpCode = "2701",
                            EndTime = "09:30 AM",
                            Room = "Rm 200",
                            Section = "H1",
                            StartTime = "08:00 AM",
                            SubjectCode = "CE101",
                            SubjectTitle = "Introduction to Civil Engineering",
                            Units = 3
                        },
                        new
                        {
                            Id = 44,
                            CourseId = 8,
                            Days = "T/Th",
                            EdpCode = "2702",
                            EndTime = "11:30 AM",
                            Room = "Rm 201",
                            Section = "H1",
                            StartTime = "10:00 AM",
                            SubjectCode = "CE102",
                            SubjectTitle = "Advanced Civil Engineering",
                            Units = 3
                        },
                        new
                        {
                            Id = 45,
                            CourseId = 8,
                            Days = "M/W",
                            EdpCode = "2703",
                            EndTime = "02:30 PM",
                            Room = "Rm 202",
                            Section = "H1",
                            StartTime = "01:00 PM",
                            SubjectCode = "CE103",
                            SubjectTitle = "Civil Engineering Principles",
                            Units = 3
                        },
                        new
                        {
                            Id = 46,
                            CourseId = 8,
                            Days = "T/Th",
                            EdpCode = "2704",
                            EndTime = "04:00 PM",
                            Room = "Rm 203",
                            Section = "H1",
                            StartTime = "02:30 PM",
                            SubjectCode = "CE104",
                            SubjectTitle = "Applied Civil Engineering",
                            Units = 3
                        },
                        new
                        {
                            Id = 47,
                            CourseId = 8,
                            Days = "F",
                            EdpCode = "2705",
                            EndTime = "10:30 AM",
                            Room = "Rm 204",
                            Section = "H1",
                            StartTime = "09:00 AM",
                            SubjectCode = "CE105",
                            SubjectTitle = "Civil Engineering Lab",
                            Units = 2
                        },
                        new
                        {
                            Id = 48,
                            CourseId = 8,
                            Days = "M/W",
                            EdpCode = "2706",
                            EndTime = "04:30 PM",
                            Room = "Rm 205",
                            Section = "H1",
                            StartTime = "03:00 PM",
                            SubjectCode = "CE106",
                            SubjectTitle = "Seminar in Civil Engineering",
                            Units = 3
                        },
                        new
                        {
                            Id = 49,
                            CourseId = 9,
                            Days = "M/W",
                            EdpCode = "2801",
                            EndTime = "09:30 AM",
                            Room = "Rm 200",
                            Section = "I1",
                            StartTime = "08:00 AM",
                            SubjectCode = "CPE101",
                            SubjectTitle = "Introduction to Computer Engineering",
                            Units = 3
                        },
                        new
                        {
                            Id = 50,
                            CourseId = 9,
                            Days = "T/Th",
                            EdpCode = "2802",
                            EndTime = "11:30 AM",
                            Room = "Rm 201",
                            Section = "I1",
                            StartTime = "10:00 AM",
                            SubjectCode = "CPE102",
                            SubjectTitle = "Advanced Computer Engineering",
                            Units = 3
                        },
                        new
                        {
                            Id = 51,
                            CourseId = 9,
                            Days = "M/W",
                            EdpCode = "2803",
                            EndTime = "02:30 PM",
                            Room = "Rm 202",
                            Section = "I1",
                            StartTime = "01:00 PM",
                            SubjectCode = "CPE103",
                            SubjectTitle = "Computer Engineering Principles",
                            Units = 3
                        },
                        new
                        {
                            Id = 52,
                            CourseId = 9,
                            Days = "T/Th",
                            EdpCode = "2804",
                            EndTime = "04:00 PM",
                            Room = "Rm 203",
                            Section = "I1",
                            StartTime = "02:30 PM",
                            SubjectCode = "CPE104",
                            SubjectTitle = "Applied Computer Engineering",
                            Units = 3
                        },
                        new
                        {
                            Id = 53,
                            CourseId = 9,
                            Days = "F",
                            EdpCode = "2805",
                            EndTime = "10:30 AM",
                            Room = "Rm 204",
                            Section = "I1",
                            StartTime = "09:00 AM",
                            SubjectCode = "CPE105",
                            SubjectTitle = "Computer Engineering Lab",
                            Units = 2
                        },
                        new
                        {
                            Id = 54,
                            CourseId = 9,
                            Days = "M/W",
                            EdpCode = "2806",
                            EndTime = "04:30 PM",
                            Room = "Rm 205",
                            Section = "I1",
                            StartTime = "03:00 PM",
                            SubjectCode = "CPE106",
                            SubjectTitle = "Seminar in Computer Engineering",
                            Units = 3
                        },
                        new
                        {
                            Id = 55,
                            CourseId = 10,
                            Days = "M/W",
                            EdpCode = "2901",
                            EndTime = "09:30 AM",
                            Room = "Rm 200",
                            Section = "J1",
                            StartTime = "08:00 AM",
                            SubjectCode = "TM101",
                            SubjectTitle = "Introduction to Tourism",
                            Units = 3
                        },
                        new
                        {
                            Id = 56,
                            CourseId = 10,
                            Days = "T/Th",
                            EdpCode = "2902",
                            EndTime = "11:30 AM",
                            Room = "Rm 201",
                            Section = "J1",
                            StartTime = "10:00 AM",
                            SubjectCode = "TM102",
                            SubjectTitle = "Advanced Tourism",
                            Units = 3
                        },
                        new
                        {
                            Id = 57,
                            CourseId = 10,
                            Days = "M/W",
                            EdpCode = "2903",
                            EndTime = "02:30 PM",
                            Room = "Rm 202",
                            Section = "J1",
                            StartTime = "01:00 PM",
                            SubjectCode = "TM103",
                            SubjectTitle = "Tourism Principles",
                            Units = 3
                        },
                        new
                        {
                            Id = 58,
                            CourseId = 10,
                            Days = "T/Th",
                            EdpCode = "2904",
                            EndTime = "04:00 PM",
                            Room = "Rm 203",
                            Section = "J1",
                            StartTime = "02:30 PM",
                            SubjectCode = "TM104",
                            SubjectTitle = "Applied Tourism",
                            Units = 3
                        },
                        new
                        {
                            Id = 59,
                            CourseId = 10,
                            Days = "F",
                            EdpCode = "2905",
                            EndTime = "10:30 AM",
                            Room = "Rm 204",
                            Section = "J1",
                            StartTime = "09:00 AM",
                            SubjectCode = "TM105",
                            SubjectTitle = "Tourism Lab",
                            Units = 2
                        },
                        new
                        {
                            Id = 60,
                            CourseId = 10,
                            Days = "M/W",
                            EdpCode = "2906",
                            EndTime = "04:30 PM",
                            Room = "Rm 205",
                            Section = "J1",
                            StartTime = "03:00 PM",
                            SubjectCode = "TM106",
                            SubjectTitle = "Seminar in Tourism",
                            Units = 3
                        },
                        new
                        {
                            Id = 61,
                            CourseId = 11,
                            Days = "M/W",
                            EdpCode = "3001",
                            EndTime = "09:30 AM",
                            Room = "Rm 200",
                            Section = "K1",
                            StartTime = "08:00 AM",
                            SubjectCode = "HM101",
                            SubjectTitle = "Introduction to Hospitality",
                            Units = 3
                        },
                        new
                        {
                            Id = 62,
                            CourseId = 11,
                            Days = "T/Th",
                            EdpCode = "3002",
                            EndTime = "11:30 AM",
                            Room = "Rm 201",
                            Section = "K1",
                            StartTime = "10:00 AM",
                            SubjectCode = "HM102",
                            SubjectTitle = "Advanced Hospitality",
                            Units = 3
                        },
                        new
                        {
                            Id = 63,
                            CourseId = 11,
                            Days = "M/W",
                            EdpCode = "3003",
                            EndTime = "02:30 PM",
                            Room = "Rm 202",
                            Section = "K1",
                            StartTime = "01:00 PM",
                            SubjectCode = "HM103",
                            SubjectTitle = "Hospitality Principles",
                            Units = 3
                        },
                        new
                        {
                            Id = 64,
                            CourseId = 11,
                            Days = "T/Th",
                            EdpCode = "3004",
                            EndTime = "04:00 PM",
                            Room = "Rm 203",
                            Section = "K1",
                            StartTime = "02:30 PM",
                            SubjectCode = "HM104",
                            SubjectTitle = "Applied Hospitality",
                            Units = 3
                        },
                        new
                        {
                            Id = 65,
                            CourseId = 11,
                            Days = "F",
                            EdpCode = "3005",
                            EndTime = "10:30 AM",
                            Room = "Rm 204",
                            Section = "K1",
                            StartTime = "09:00 AM",
                            SubjectCode = "HM105",
                            SubjectTitle = "Hospitality Lab",
                            Units = 2
                        },
                        new
                        {
                            Id = 66,
                            CourseId = 11,
                            Days = "M/W",
                            EdpCode = "3006",
                            EndTime = "04:30 PM",
                            Room = "Rm 205",
                            Section = "K1",
                            StartTime = "03:00 PM",
                            SubjectCode = "HM106",
                            SubjectTitle = "Seminar in Hospitality",
                            Units = 3
                        },
                        new
                        {
                            Id = 67,
                            CourseId = 12,
                            Days = "M/W",
                            EdpCode = "3101",
                            EndTime = "09:30 AM",
                            Room = "Rm 200",
                            Section = "L1",
                            StartTime = "08:00 AM",
                            SubjectCode = "NUR101",
                            SubjectTitle = "Introduction to Nursing",
                            Units = 3
                        },
                        new
                        {
                            Id = 68,
                            CourseId = 12,
                            Days = "T/Th",
                            EdpCode = "3102",
                            EndTime = "11:30 AM",
                            Room = "Rm 201",
                            Section = "L1",
                            StartTime = "10:00 AM",
                            SubjectCode = "NUR102",
                            SubjectTitle = "Advanced Nursing",
                            Units = 3
                        },
                        new
                        {
                            Id = 69,
                            CourseId = 12,
                            Days = "M/W",
                            EdpCode = "3103",
                            EndTime = "02:30 PM",
                            Room = "Rm 202",
                            Section = "L1",
                            StartTime = "01:00 PM",
                            SubjectCode = "NUR103",
                            SubjectTitle = "Nursing Principles",
                            Units = 3
                        },
                        new
                        {
                            Id = 70,
                            CourseId = 12,
                            Days = "T/Th",
                            EdpCode = "3104",
                            EndTime = "04:00 PM",
                            Room = "Rm 203",
                            Section = "L1",
                            StartTime = "02:30 PM",
                            SubjectCode = "NUR104",
                            SubjectTitle = "Applied Nursing",
                            Units = 3
                        },
                        new
                        {
                            Id = 71,
                            CourseId = 12,
                            Days = "F",
                            EdpCode = "3105",
                            EndTime = "10:30 AM",
                            Room = "Rm 204",
                            Section = "L1",
                            StartTime = "09:00 AM",
                            SubjectCode = "NUR105",
                            SubjectTitle = "Nursing Lab",
                            Units = 2
                        },
                        new
                        {
                            Id = 72,
                            CourseId = 12,
                            Days = "M/W",
                            EdpCode = "3106",
                            EndTime = "04:30 PM",
                            Room = "Rm 205",
                            Section = "L1",
                            StartTime = "03:00 PM",
                            SubjectCode = "NUR106",
                            SubjectTitle = "Seminar in Nursing",
                            Units = 3
                        },
                        new
                        {
                            Id = 73,
                            CourseId = 13,
                            Days = "M/W",
                            EdpCode = "3201",
                            EndTime = "09:30 AM",
                            Room = "Rm 200",
                            Section = "M1",
                            StartTime = "08:00 AM",
                            SubjectCode = "BA101",
                            SubjectTitle = "Introduction to Business",
                            Units = 3
                        },
                        new
                        {
                            Id = 74,
                            CourseId = 13,
                            Days = "T/Th",
                            EdpCode = "3202",
                            EndTime = "11:30 AM",
                            Room = "Rm 201",
                            Section = "M1",
                            StartTime = "10:00 AM",
                            SubjectCode = "BA102",
                            SubjectTitle = "Advanced Business",
                            Units = 3
                        },
                        new
                        {
                            Id = 75,
                            CourseId = 13,
                            Days = "M/W",
                            EdpCode = "3203",
                            EndTime = "02:30 PM",
                            Room = "Rm 202",
                            Section = "M1",
                            StartTime = "01:00 PM",
                            SubjectCode = "BA103",
                            SubjectTitle = "Business Principles",
                            Units = 3
                        },
                        new
                        {
                            Id = 76,
                            CourseId = 13,
                            Days = "T/Th",
                            EdpCode = "3204",
                            EndTime = "04:00 PM",
                            Room = "Rm 203",
                            Section = "M1",
                            StartTime = "02:30 PM",
                            SubjectCode = "BA104",
                            SubjectTitle = "Applied Business",
                            Units = 3
                        },
                        new
                        {
                            Id = 77,
                            CourseId = 13,
                            Days = "F",
                            EdpCode = "3205",
                            EndTime = "10:30 AM",
                            Room = "Rm 204",
                            Section = "M1",
                            StartTime = "09:00 AM",
                            SubjectCode = "BA105",
                            SubjectTitle = "Business Lab",
                            Units = 2
                        },
                        new
                        {
                            Id = 78,
                            CourseId = 13,
                            Days = "M/W",
                            EdpCode = "3206",
                            EndTime = "04:30 PM",
                            Room = "Rm 205",
                            Section = "M1",
                            StartTime = "03:00 PM",
                            SubjectCode = "BA106",
                            SubjectTitle = "Seminar in Business",
                            Units = 3
                        });
                });

            modelBuilder.Entity("EnrollmentSystem.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "registrar@mapplewood.edu",
                            PasswordHash = "$2a$11$16uHNH4dKW/v1z4Wrb/exujzPpsdGNo4g23aud/bC4olXKOTl8veu",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "john@mapplewood.edu",
                            PasswordHash = "$2a$11$16uHNH4dKW/v1z4Wrb/exujzPpsdGNo4g23aud/bC4olXKOTl8veu",
                            Role = "Student"
                        });
                });

            modelBuilder.Entity("EnrollmentSystem.Api.Models.YearLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("YearLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "1st Year"
                        },
                        new
                        {
                            Id = 2,
                            Name = "2nd Year"
                        },
                        new
                        {
                            Id = 3,
                            Name = "3rd Year"
                        },
                        new
                        {
                            Id = 4,
                            Name = "4th Year"
                        },
                        new
                        {
                            Id = 5,
                            Name = "5th Year"
                        });
                });

            modelBuilder.Entity("EnrollmentSystem.Api.Models.Enrollment", b =>
                {
                    b.HasOne("EnrollmentSystem.Api.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnrollmentSystem.Api.Models.Subject", "Subject")
                        .WithMany("Enrollments")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("EnrollmentSystem.Api.Models.Student", b =>
                {
                    b.HasOne("EnrollmentSystem.Api.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId");

                    b.HasOne("EnrollmentSystem.Api.Models.YearLevel", "YearLevel")
                        .WithMany()
                        .HasForeignKey("YearLevelId");

                    b.Navigation("Course");

                    b.Navigation("YearLevel");
                });

            modelBuilder.Entity("EnrollmentSystem.Api.Models.Subject", b =>
                {
                    b.HasOne("EnrollmentSystem.Api.Models.Course", "Course")
                        .WithMany("Subjects")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("EnrollmentSystem.Api.Models.Course", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("EnrollmentSystem.Api.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("EnrollmentSystem.Api.Models.Subject", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
